name: my_hesab_ketab
description: Go Dutch

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  font_awesome_flutter: ^10.2.1
  url_launcher: ^6.1.5
  provider: ^6.0.3
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: poppins-light
      fonts:
        - asset: assets/fonts/Poppins-ExtraLight.ttf
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
